--- #    本地环境 ---------------------
#redis:
#  host:  127.0.0.1
#  port:  6379
#  password:
#  timeout: 3600
#  pool:
#    maxTotal: 1024
#    maxWaitMillis: 1000
#    timeBetweenEvictionRunsMillis: 30000
#    minEvictableIdleTimeMillis: 30000
#    testOnBorrow: true
#    max-wait: 1000
#    max-idle: 500
spring:
  redis:
      #host: 192.168.3.170
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
      timeout: 3000ms
      # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
      jedis:
        pool:
          # 最大空闲连接数
          max-idle: 1024
          # 最小空闲连接数
          min-idle: 300
          # 等待可用连接的最大时间，负数为不限制
          max-wait:  -1ms
          # 最大活跃连接数，负数为不限制
          max-active: -1
    #配置http编码（非常重要，否则中文乱码）

cms:
  web:
    domain: http://localhost:8088
